# Generated by Django 3.0.1 on 2020-02-10 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorgasmodel',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
