# Generated by Django 3.0.1 on 2020-02-10 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200210_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorgasmodel',
            name='time_stamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
