# Generated by Django 3.0.1 on 2020-02-11 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200210_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorgasmodel',
            name='no_tiang',
            field=models.CharField(choices=[(1, 'Tiang A'), (2, 'Tiang B'), (3, 'Tiang C')], default=None, max_length=10),
        ),
    ]
