# Generated by Django 3.0.1 on 2020-02-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200211_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorgasmodel',
            name='no_tiang',
            field=models.CharField(choices=[('Tiang A', 1), ('Tiang B', 2), ('Tiang C', 3)], default=None, max_length=10),
        ),
    ]
