# Generated by Django 3.0.1 on 2020-02-12 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20200211_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorgasmodel',
            name='sensor_value',
            field=models.IntegerField(),
        ),
    ]
